import {
  Activity, ArrowLeft, BadgeCheck, BadgePercent, BarChart3, Briefcase, Building2, CalendarClock,
  CalendarDays, CalendarPlus, CircleHelp, ClipboardList, Coins, ContactRound, CreditCard, FileText,
  Flag, Gauge, Handshake, House, Images, Inbox, LayoutDashboard, LayoutTemplate, LifeBuoy, Link2,
  Megaphone, MessageSquare, MousePointerClick, Newspaper, Package, PackageCheck, Palette,
  PanelsTopLeft, Plug, Scale, ScanSearch, ScrollText, Settings, Share2, Shield, ShieldAlert,
  ShieldCheck, ShoppingBag, Sparkles, Star, Store, Target, TrendingUp, UserCircle2, UserPlus,
  UserRound, Users, UsersRound, Wallet, WandSparkles, Workflow, Calendar,
  type LucideIcon,
} from 'lucide-react'
import type { NavIconKey } from '@/lib/navigation/types'

/** One stable icon per canonical module — never varied page to page. */
export const NAV_ICONS: Record<NavIconKey, LucideIcon> = {
  home: House,
  strategy: Target,
  campaigns: Megaphone,
  calendar: Calendar,
  studio: WandSparkles,
  brand: Palette,
  links: Link2,
  templates: LayoutTemplate,
  social: Share2,
  advertising: MousePointerClick,
  messaging: MessageSquare,
  web: PanelsTopLeft,
  seo: ScanSearch,
  creators: Users,
  marketplace: Store,
  partnerships: Handshake,
  reputation: Newspaper,
  community: UsersRound,
  events: CalendarDays,
  inbox: Inbox,
  audiences: ContactRound,
  approvals: BadgeCheck,
  analytics: BarChart3,
  finance: Wallet,
  reports: ClipboardList,
  automations: Workflow,
  operations: Gauge,
  settings: Settings,
  clients: Briefcase,
  dashboard: LayoutDashboard,
  profile: UserCircle2,
  listings: Package,
  requests: ClipboardList,
  quotes: FileText,
  orders: ShoppingBag,
  deliveries: PackageCheck,
  messages: MessageSquare,
  availability: CalendarClock,
  reviews: Star,
  disputes: ShieldAlert,
  earnings: Coins,
  workspaces: Building2,
  users: Users,
  billing: CreditCard,
  safety: ShieldCheck,
  connections: Plug,
  support: LifeBuoy,
  compliance: Scale,
  flags: Flag,
  audit: ScrollText,
  programme: BadgePercent,
  assets: Images,
  conversions: TrendingUp,
  commissions: Coins,
  content: FileText,
  schedule: CalendarPlus,
  invite: UserPlus,
  help: CircleHelp,
  changelog: Sparkles,
  status: Activity,
  account: UserRound,
  admin: Shield,
  return: ArrowLeft,
}
