"""Builds src/components/brand-assets/ui/world-dots.ts from Natural Earth 110m
country boundaries (world-atlas@2.0.2, public domain): a 3-degree dot grid of
land, each dot tagged with its ISO 3166 alpha-2 code where known.

The Rights coverage map colours these dots from real licence territories, so
the map is data, not a picture.   Run: python scripts/build-world-dots.py
"""
import json, os
T = json.load(open(os.path.join(os.path.dirname(__file__), 'data', 'countries-110m.json')))
sx, sy = T['transform']['scale']; tx, ty = T['transform']['translate']
arcs = []
for arc in T['arcs']:
    x = y = 0; pts = []
    for dx, dy in arc:
        x += dx; y += dy; pts.append((x * sx + tx, y * sy + ty))
    arcs.append(pts)
def ring(idx):
    out = []
    for i in idx:
        seg = arcs[i] if i >= 0 else list(reversed(arcs[~i]))
        out.extend(seg if not out else seg[1:])
    return out
# ISO numeric -> alpha-2 for every country the territory catalogue can reference,
# plus other large land masses so they read as "not covered" rather than blank.
NUM = {'840':'US','124':'CA','484':'MX','826':'GB','276':'DE','250':'FR','724':'ES','380':'IT','528':'NL','752':'SE',
 '784':'AE','710':'ZA','616':'PL','372':'IE','036':'AU','554':'NZ','392':'JP','702':'SG','410':'KR','356':'IN',
 '076':'BR','032':'AR','152':'CL','170':'CO','156':'CN','643':'RU','818':'EG','566':'NG','404':'KE','682':'SA',
 '360':'ID','608':'PH','764':'TH','704':'VN','458':'MY','586':'PK','050':'BD','792':'TR','364':'IR','012':'DZ',
 '504':'MA','231':'ET','180':'CD','024':'AO','604':'PE','862':'VE','068':'BO','578':'NO','246':'FI','208':'DK',
 '756':'CH','040':'AT','056':'BE','620':'PT','300':'GR','804':'UA','642':'RO','348':'HU','203':'CZ','398':'KZ',
 '496':'MN','104':'MM','304':'GL','376':'IL','368':'IQ','434':'LY','729':'SD','148':'TD','562':'NE','466':'ML'}
countries = []
for g in T['objects']['countries']['geometries']:
    polys = g['arcs'] if g['type'] == 'MultiPolygon' else [g['arcs']] if g['type'] == 'Polygon' else []
    rings = [ring(r) for p in polys for r in p]
    xs = [p[0] for r in rings for p in r]; ys = [p[1] for r in rings for p in r]
    if xs: countries.append((NUM.get(str(g.get('id', '')).zfill(3), ''), rings, (min(xs), min(ys), max(xs), max(ys))))
def inside(x, y, r):
    c = False; j = len(r) - 1
    for i in range(len(r)):
        xi, yi = r[i]; xj, yj = r[j]
        if (yi > y) != (yj > y) and x < (xj - xi) * (y - yi) / (yj - yi + 1e-12) + xi: c = not c
        j = i
    return c
STEP = 3
dots = []
for lat in range(84, -58, -STEP):
    for lon in range(-180 + STEP // 2, 180, STEP):
        for iso, rings, (x0, y0, x1, y1) in countries:
            if x0 <= lon <= x1 and y0 <= lat <= y1 and sum(inside(lon, lat, r) for r in rings) % 2 == 1:
                dots.append(f'{(lon + 180) // STEP},{(84 - lat) // STEP},{iso}'); break
out = os.path.join(os.path.dirname(__file__), '..', 'src', 'components', 'brand-assets', 'ui', 'world-dots.ts')
with open(out, 'w', encoding='utf-8') as f:
    f.write('// GENERATED by scripts/build-world-dots.py from Natural Earth 110m (public domain). Do not edit.\n')
    f.write(f'// {len(dots)} land dots on a {STEP}° grid: "col,row,ISO" (ISO empty when not catalogued).\n')
    f.write(f'export const WORLD_STEP = {STEP}\nexport const WORLD_COLS = {360 // STEP}\nexport const WORLD_ROWS = {(84 + 57) // STEP + 1}\n')
    f.write(f"export const WORLD_DOTS = '{';'.join(dots)}'\n")
print(len(dots), 'dots;', sum(1 for d in dots if not d.endswith(',')), 'tagged')
