"""Builds src/components/strategy/world-paths.ts from Natural Earth 110m country
boundaries (world-atlas@2.0.2, public domain): one simplified SVG path per
country, tagged with its ISO 3166 alpha-2 code where known.

The Strategy audience map fills these paths from real aggregated audience
regions, so the map is data, not a picture.   Run: python scripts/build-world-paths.py
"""
import json, math, os

HERE = os.path.dirname(__file__)
T = json.load(open(os.path.join(HERE, 'data', 'countries-110m.json')))
sx, sy = T['transform']['scale']; tx, ty = T['transform']['translate']

arcs = []
for arc in T['arcs']:
    x = y = 0; pts = []
    for dx, dy in arc:
        x += dx; y += dy; pts.append((x * sx + tx, y * sy + ty))
    arcs.append(pts)

def ring(idx):
    out = []
    for i in idx:
        seg = arcs[i] if i >= 0 else list(reversed(arcs[~i]))
        out.extend(seg if not out else seg[1:])
    return out

NUM = {'840':'US','124':'CA','484':'MX','826':'GB','276':'DE','250':'FR','724':'ES','380':'IT','528':'NL','752':'SE',
 '784':'AE','710':'ZA','616':'PL','372':'IE','036':'AU','554':'NZ','392':'JP','702':'SG','410':'KR','356':'IN',
 '076':'BR','032':'AR','152':'CL','170':'CO','156':'CN','643':'RU','818':'EG','566':'NG','404':'KE','682':'SA',
 '360':'ID','608':'PH','764':'TH','704':'VN','458':'MY','586':'PK','050':'BD','792':'TR','364':'IR','012':'DZ',
 '504':'MA','231':'ET','180':'CD','024':'AO','604':'PE','862':'VE','068':'BO','578':'NO','246':'FI','208':'DK',
 '756':'CH','040':'AT','056':'BE','620':'PT','300':'GR','804':'UA','642':'RO','348':'HU','203':'CZ','398':'KZ',
 '496':'MN','104':'MM','304':'GL','376':'IL','368':'IQ','434':'LY','729':'SD','148':'TD','562':'NE','466':'ML',
 '858':'UY','600':'PY','218':'EC','192':'CU','320':'GT','340':'HN','558':'NI','591':'PA','188':'CR','332':'HT',
 '214':'DO','716':'ZW','894':'ZM','508':'MZ','454':'MW','834':'TZ','800':'UG','646':'RW','288':'GH','384':'CI',
 '686':'SN','324':'GN','430':'LR','694':'SL','478':'MR','120':'CM','140':'CF','178':'CG','266':'GA','072':'BW',
 '516':'NA','426':'LS','748':'SZ','450':'MG','706':'SO','232':'ER','262':'DJ','728':'SS','788':'TN','400':'JO',
 '760':'SY','422':'LB','887':'YE','512':'OM','414':'KW','634':'QA','048':'BH','004':'AF','860':'UZ','795':'TM',
 '762':'TJ','417':'KG','524':'NP','064':'BT','144':'LK','116':'KH','418':'LA','408':'KP','158':'TW','598':'PG',
 '090':'SB','548':'VU','242':'FJ','352':'IS','112':'BY','440':'LT','428':'LV','233':'EE','498':'MD','703':'SK',
 '705':'SI','191':'HR','070':'BA','688':'RS','499':'ME','807':'MK','008':'AL','100':'BG','196':'CY','268':'GE',
 '051':'AM','031':'AZ','626':'TL','096':'BN','732':'EH','204':'BJ','768':'TG','854':'BF','624':'GW','226':'GQ',
 '108':'BI','174':'KM','238':'FK','260':'TF','010':'AQ','630':'PR','044':'BS','780':'TT','084':'BZ','740':'SR',
 '328':'GY','254':'GF','540':'NC','016':'AS','442':'LU','-99':'XK'}

W, H_TOP, H_BOTTOM = 360.0, 84.0, -58.0   # crop Antarctica and the far south
Y_STRETCH = 1.22                          # closer to the Miller-style proportions of the design

def project(lon, lat):
    return (lon + 180.0, (H_TOP - lat) * Y_STRETCH)

def simplify(points, tolerance=0.45):
    if len(points) < 4:
        return points
    kept = [points[0]]
    for p in points[1:-1]:
        if math.hypot(p[0] - kept[-1][0], p[1] - kept[-1][1]) >= tolerance:
            kept.append(p)
    kept.append(points[-1])
    return kept

countries = []
for g in T['objects']['countries']['geometries']:
    iso = NUM.get(str(g.get('id', '')).zfill(3), NUM.get(str(g.get('id', '')), ''))
    if iso in ('AQ', 'TF'):
        continue
    polys = g['arcs'] if g['type'] == 'MultiPolygon' else [g['arcs']] if g['type'] == 'Polygon' else []
    parts = []
    for p in polys:
        for r in p:
            pts = [project(lon, lat) for lon, lat in ring(r) if lat >= H_BOTTOM]
            pts = simplify(pts)
            if len(pts) < 3:
                continue
            # Skip rings wrapping the antimeridian badly (tiny Fiji/Russia slivers).
            xs = [q[0] for q in pts]
            if max(xs) - min(xs) > 300:
                continue
            parts.append('M' + 'L'.join(f'{x:.1f},{y:.1f}' for x, y in pts) + 'Z')
    if parts:
        countries.append((iso, g.get('properties', {}).get('name', ''), ''.join(parts)))

out = os.path.join(HERE, '..', 'src', 'components', 'strategy', 'world-paths.ts')
with open(out, 'w', encoding='utf8', newline='\n') as f:
    f.write('// GENERATED by scripts/build-world-paths.py from Natural Earth 110m (public domain). Do not edit.\n')
    f.write(f'export const WORLD_VIEWBOX = "0 0 {W:.0f} {(H_TOP - H_BOTTOM) * Y_STRETCH:.0f}"\n')
    f.write('export const WORLD_PATHS: { iso: string; name: string; d: string }[] = [\n')
    for iso, name, d in countries:
        f.write(f'  {{ iso: {json.dumps(iso)}, name: {json.dumps(name)}, d: {json.dumps(d)} }},\n')
    f.write(']\n')
print('countries', len(countries), 'bytes', os.path.getsize(out))
